---
title: "Act 5 en clase y tarea"
author: "Liliana Contreras Segundo"
date:    "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: show
    theme: bootstrap
    word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Eliminacion Gaussiana con pivoteo parcial

El sistema a resolver es:

5x+2y-3z+4w=-1

-x+y+z-3w=2

6x+6y+4z+w=0

x-y-z+w=2

```{r}
valoresc <- c(5, -1,6,1,2,1,6,-1,-3,1,4,-1,4,-3,1,1, -1, 2, 0, 2)
A<- matrix(t(valoresc), nrow = 4)
(A)
```


## primer pivoteo ( cambio de columnas)

```{r}
R1<- A[3,]; (R1)
R3<- A[1,]; (R3)
R2<- A[2,]; (R2)
R4<- A[4,]; (R4)
NuevaA <- rbind(R1,R2, R3, R4)
(NuevaA)
```

### primera eliminación

```{r}
m1 <- -NuevaA[2,1]/NuevaA[1,1]; (m1)
m2 <- -NuevaA[3,1]/NuevaA[1,1]; (m2)
m3 <- -NuevaA[4,1]/NuevaA[1,1]; (m3)

R2<- m1*NuevaA[1,] + NuevaA[2,]; (R2)
R3<- m2*NuevaA[1,] + NuevaA[3,]; (R3)
R4<- m3*NuevaA[1,] + NuevaA[4,]; (R4)
NuevaA <- rbind(R1, R2, R3, R4)
cat("Matriz después de primera eliminación:\n")
(NuevaA)
```
  
  
  
## pivoteo 2

```{r}
sub_matriz <- NuevaA[2:4,]
max_fila2 <- which.max(abs(sub_matriz[,2])) + 1
cat("Nueva fila pivote:", max_fila2, "\n")

# Reorganizar filas
temp <- NuevaA[2,]
NuevaA[2,] <- NuevaA[max_fila2,]
NuevaA[max_fila2,] <- temp

# Actualizar R1, R2, R3, R4
R1 <- NuevaA[1,]
R2 <- NuevaA[2,]
R3 <- NuevaA[3,]
R4 <- NuevaA[4,]
cat("Matriz después del segundo pivoteo:\n")
(NuevaA)
```

### eliminación 2

```{r}
m4<- -NuevaA[3,2]/NuevaA[2,2]; (m4)
m5<- -NuevaA[4,2]/NuevaA[2,2]; (m5)

R3<- m4*NuevaA[2,] + NuevaA[3,]; (R3)
R4<- m5*NuevaA[2,] + NuevaA[4,]; (R4)
NuevaA <- rbind(R1, R2, R3, R4)
cat("Matriz después de segunda eliminación:\n")
(NuevaA)
```
## Pivoteo 3
```{r}
sub_matriz <- NuevaA[3:4,]
max_fila3 <- which.max(abs(sub_matriz[,3])) + 2
cat("Nueva fila pivote:", max_fila3, "\n")

temp <- NuevaA[3,]
NuevaA[3,] <- NuevaA[max_fila3,]
NuevaA[max_fila3,] <- temp

R1 <- NuevaA[1,]
R2 <- NuevaA[2,]
R3 <- NuevaA[3,]
R4 <- NuevaA[4,]
cat("Matriz después del tercer pivoteo:\n")
(NuevaA)
```
### Eliminación 3

```{r}
m6<- -NuevaA[4,3]/NuevaA[3,3]; (m6)
R4<- m6*NuevaA[3,] + NuevaA[4,]; (R4)
NuevaA <- rbind(R1, R2, R3, R4)
cat("Matriz después de tercera eliminación:\n")
(NuevaA)
```
## Se terminan los pivoteos y ahora pura eliminación 
### Eliminación 4

```{r}
m7<- -NuevaA[3,4]/NuevaA[4,4]; (m7)
m8<- -NuevaA[2,4]/NuevaA[4,4]; (m8)
m9<- -NuevaA[1,4]/NuevaA[4,4]; (m9)

R3<- m7 * NuevaA[4,] + NuevaA[3,]; (R3)
R2<- m8 * NuevaA[4,] + NuevaA[2,]; (R2)
R1<- m9 * NuevaA[4,] + NuevaA[1,]; (R1)
NuevaA<- rbind(R1, R2, R3, R4)
cat("Matriz de eliminacion:\n")
(NuevaA)
```
### Eliminación 5
```{r}
m10<- -NuevaA[2,3]/NuevaA[3,3]; (m10)
m11<- -NuevaA[1,3]/NuevaA[3,3]; (m11)

R2<- m10 * NuevaA[3,] + NuevaA[2,]; (R2)
R1<- m11 * NuevaA[3,] + NuevaA[1,]; (R1)
NuevaA<- rbind(R1, R2, R3, R4)
cat("Matriz de eliminación:\n")
(NuevaA)
```
### Eliminación 6

```{r}
m12<- -NuevaA[1,2]/NuevaA[2,2]; (m12)
R1<- m12 * NuevaA[2,] + NuevaA[1,]; (R1)
NuevaA<- rbind(R1, R2, R3, R4)
cat("Matriz final (diagonalizada):\n")
(NuevaA)
```
# Soluciones finales:
```{r}
x<- NuevaA[1,5] / NuevaA[1,1]
y<- NuevaA[2,5] / NuevaA[2,2]
z<- NuevaA[3,5] / NuevaA[3,3]
w<- NuevaA[4,5] / NuevaA[4,4]

cat("SOLUCIONES FINALES:\n")
cat("x =", round(x, 4), "\n")
cat("y =", round(y, 4), "\n") 
cat("z =", round(z, 4), "\n")
cat("w =", round(w, 4), "\n")

# Verificación
cat("\nVERIFICACIÓN:\n")
cat("Ecuación 1:", round(5*x + 2*y - 3*z + 4*w, 4), "(debe ser -1)\n")
cat("Ecuación 2:", round(-x + y + z - 3*w, 4), "(debe ser 2)\n")
cat("Ecuación 3:", round(6*x + 6*y + 4*z + w, 4), "(debe ser 0)\n")
cat("Ecuación 4:", round(x - y - z + w, 4), "(debe ser 2)\n")
```
